### PR TITLE
add type check

### PR DESCRIPTION
**Pull request by SamVerschueren**
Started with only :lipstick: but didn't want to create 2 PRs.

Should I expose the types from `lib/utils.js` instead of defining them twice?

I will ES2015ify if this one gets merged. Not sure if we should do an intermediate release?

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Should I expose the types from lib/utils.js instead of defining them twice?

👍 

> Not sure if we should do an intermediate release?

Nah

**Comment by SamVerschueren** [comment]
Done

**Comment by SamVerschueren** [comment]
Alright, thanks :) 🎉 

@kevva Could you release this one and [viewport-list](https://github.com/kevva/viewport-list), both major, so I can upgrade `pageres` :).

**Comment by SamVerschueren** [comment]
Oops, have to ES2015ify first :p.

**Comment by sindresorhus** [comment]
@SamVerschueren Aren't we gonna ES2015ify this one first?

**Comment by sindresorhus** [comment]
Yup

**Pull request merged**
